In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import time
from selenium import webdriver

In [2]:
team_url = 'http://www.espn.com/nba/players/_/position/pf/league/nba'
request = requests.get(team_url)
soup = BeautifulSoup(request.text, 'html.parser')

In [35]:
[int(x["href"].split("/id/")[1].split("/")[0]) for x in soup.findAll('a') if "player/" in x["href"]]

[4066261,
 2983,
 3918424,
 4248,
 3032977,
 4066490,
 1975,
 4277848,
 3064427,
 2578240,
 4269,
 3948153,
 3912292,
 3132042,
 4278067,
 3908845,
 4066650,
 4066367,
 2490620,
 6583,
 3919335,
 3914285,
 3113587,
 4066264,
 4278049,
 3428,
 3064290,
 2991070,
 6589,
 2327577,
 3209,
 3989,
 4066648,
 3907408,
 2991055,
 2184,
 6592,
 4017839,
 3143565,
 3213,
 2767,
 4065654,
 4277961,
 4067045,
 3999,
 4065660,
 2960236,
 3134907,
 3936296,
 3136746,
 4066425,
 3155535,
 3449,
 4066336,
 3451,
 4066731,
 4341,
 3914283,
 3015,
 6461,
 3059306,
 2490089,
 2580365,
 3056602,
 2489663,
 3149059,
 3056600,
 3133817,
 4264,
 2488653,
 4278103,
 4278104,
 3064482,
 3102531,
 2990962,
 3064514,
 3155942,
 4423309,
 3032978,
 6622,
 3149673,
 3923253,
 4401415,
 3908806,
 4065836,
 3906671,
 4065648,
 3276,
 3033,
 4278077,
 3078284,
 3912848,
 4278078,
 4066218,
 3064528,
 2797,
 3136491,
 3058254,
 4278509,
 3244]

In [38]:
[x.text.split(", ")[1] + " " + x.text.split(", ")[0] for x in soup.findAll('a') if "player/" in x["href"]]

['Bam Adebayo',
 'LaMarcus Aldridge',
 'Kyle Alexander',
 'Al-Farouq Aminu',
 'Giannis Antetokounmpo',
 'Kostas Antetokounmpo',
 'Carmelo Anthony',
 'Marvin Bagley III',
 'Jordan Bell',
 'Khem Birch',
 'Nemanja Bjelica',
 'Chris Boucher',
 'Jarrell Brantley',
 'Gary Clark',
 'Nicolas Claxton',
 'John Collins',
 'Zach Collins',
 'Tyler Cook',
 'Robert Covington',
 'Anthony Davis',
 'Cheick Diallo',
 'Drew Eubanks',
 'Cristiano Felicio',
 'Wenyen Gabriel',
 'Daniel Gafford',
 'Danilo Gallinari',
 'Aaron Gordon',
 'Jerami Grant',
 'Draymond Green',
 'JaMychal Green',
 'Jeff Green',
 'Blake Griffin',
 'Rui Hachimura',
 'Donta Hall',
 'Montrezl Harrell',
 'Udonis Haslem',
 'John Henson',
 'Juan Hernangomez',
 'Kevin Hervey',
 'Al Horford',
 'Ersan Ilyasova',
 'Jonathan Isaac',
 'Jaren Jackson Jr.',
 'Alize Johnson',
 'James Johnson',
 'Mfiondu Kabengele',
 'Maxi Kleber',
 'Kyle Kuzma',
 'Skal Labissiere',
 'Vic Law',
 'T.J. Leaf',
 'Kevon Looney',
 'Kevin Love',
 'Lauri Markkanen',
 'Luc Mbah a Moute',
 'Jalen McDaniels',
 'Nicolo Melli',
 'Chimezie Metu',
 'Paul Millsap',
 'Markieff Morris',
 'Johnathan Motley',
 'Mike Muscala',
 'Larry Nance Jr.',
 'Semi Ojeleye',
 'Kelly Olynyk',
 'Tariq Owens',
 'Jabari Parker',
 'Eric Paschall',
 'Patrick Patterson',
 'Mason Plumlee',
 'Jontay Porter',
 'Michael Porter Jr.',
 'Bobby Portis',
 'Kristaps Porzingis',
 'Taurean Prince',
 'Julius Randle',
 'Domantas Sabonis',
 'Luka Samanic',
 'Dario Saric',
 'Mike Scott',
 'Pascal Siakam',
 'Chris Silva',
 'Alen Smailagic',
 'Ray Spalding',
 'Omari Spellman',
 'Caleb Swanigan',
 'Jayson Tatum',
 'Anthony Tolliver',
 'P.J. Tucker',
 'Jarred Vanderbilt',
 'Noah Vonleh',
 'Dean Wade',
 'PJ Washington',
 'Grant Williams',
 'Johnathan Williams',
 'Marvin Williams',
 'D.J. Wilson',
 'Christian Wood',
 'Kenny Wooten',
 'Thaddeus Young']

In [39]:
positions = ["pg", "sg", "sf", "pf", "c"]

In [41]:
playersdf = pd.DataFrame(columns = ["name", "espn_player_id"])

In [43]:
for position in positions:
    team_url = 'http://www.espn.com/nba/players/_/position/' + position + '/league/nba'
    request = requests.get(team_url)
    soup = BeautifulSoup(request.text, 'html.parser') 
    
    ids = [int(x["href"].split("/id/")[1].split("/")[0]) for x in soup.findAll('a') if "player/" in x["href"]]
    names = [x.text.split(", ")[1] + " " + x.text.split(", ")[0] for x in soup.findAll('a') if "player/" in x["href"]]
    
    intermediate = pd.DataFrame({"name" : names,
                                 "espn_player_id" : ids})
    
    playersdf = pd.concat([playersdf, intermediate])

In [44]:
playersdf

                   name espn_player_id
0          Jaylen Adams        3133874
1      Ryan Arcidiacono        2991047
2         D.J. Augustin           3415
3            Lonzo Ball        4066421
4            J.J. Barea           3055
..                  ...            ...
69  Robert Williams III        4066211
70          Cody Zeller        2579258
71         Tyler Zeller           6631
72           Ante Zizic        4017838
73          Ivica Zubac        4017837

[512 rows x 2 columns]

In [45]:
playersdf.to_csv("/Users/James/Desktop/Deep_Learning/nba-movement-data/rebounding_data/images/playerspictures.csv",
                 index = False)